branch-defaults:
  aws:
    environment: studiocracy-public
global:
  application_name: studiocracy-public
  default_ec2_keyname: aws-eb
  default_platform: 64bit Amazon Linux 2015.03 v1.4.3 running Ruby 2.2 (Puma)
  default_region: us-west-1
  profile: eb-cli
  sc: git
